import type { CardDefinition } from '../../../engine/types';

export const midnightHospitalCards: CardDefinition[] = [
  {
    id: 'quick_search',
    name: '快速搜查',
    basePower: 3,
    cost: 1,
    tags: ['insight'],
    rarity: 'basic',
    description: '低成本洞察行动。',
    assetId: 'card_quick_search',
  },
  {
    id: 'brace_yourself',
    name: '稳住呼吸',
    basePower: 2,
    cost: 1,
    tags: ['protection'],
    rarity: 'basic',
    description: '本次失败时，少损失 1 点理智。',
    effects: [{ type: 'REDUCE_SANITY_LOSS', amount: 1 }],
    assetId: 'card_brace_yourself',
  },
  {
    id: 'improvised_tool',
    name: '临时工具',
    basePower: 3,
    cost: 1,
    tags: ['stealth', 'escape'],
    rarity: 'basic',
    description: '适合潜行或逃生。',
    assetId: 'card_improvised_tool',
  },
  {
    id: 'run_through',
    name: '冲过去',
    basePower: 4,
    cost: 2,
    tags: ['escape', 'combat'],
    rarity: 'basic',
    description: '高风险行动，失败时生命 -1。',
    effects: [{ type: 'ON_FAILURE_DELTA', delta: { hp: -1 } }],
    assetId: 'card_run_through',
  },
  {
    id: 'pollution_noise',
    name: '污染噪声',
    basePower: 0,
    cost: 0,
    tags: [],
    rarity: 'curse',
    description: '废牌。抽到时本节点可用手牌变少。',
    assetId: 'card_pollution_noise',
  },
  {
    id: 'scene_reconstruction',
    name: '现场复盘',
    basePower: 4,
    cost: 2,
    tags: ['insight'],
    rarity: 'career',
    description: '成功时预览下一节点推荐标签。',
    effects: [{ type: 'SET_FLAG', flagKey: 'preview_next_tags', flagValue: true }],
    assetId: 'card_scene_reconstruction',
  },
  {
    id: 'medical_record_questioning',
    name: '病历追问',
    basePower: 3,
    cost: 1,
    tags: ['social', 'insight'],
    rarity: 'career',
    description: '成功时理智 +1。',
    effects: [{ type: 'ON_SUCCESS_DELTA', delta: { sanity: 1 } }],
    assetId: 'card_medical_record_questioning',
  },
  {
    id: 'logic_loop',
    name: '逻辑闭环',
    basePower: 5,
    cost: 3,
    tags: ['insight'],
    rarity: 'career',
    description: '高强度洞察卡。',
    assetId: 'card_logic_loop',
  },
  {
    id: 'calm_observation',
    name: '冷静观察',
    basePower: 2,
    cost: 1,
    tags: ['insight', 'protection'],
    rarity: 'career',
    description: '抵消一次小额理智损失。',
    effects: [{ type: 'REDUCE_SANITY_LOSS', amount: 1 }],
    assetId: 'card_calm_observation',
  },
  {
    id: 'door_breaker',
    name: '破门锤',
    basePower: 5,
    cost: 2,
    tags: ['combat'],
    rarity: 'career',
    description: '失败时生命 -1。',
    assetId: 'card_door_breaker',
  },
  {
    id: 'guard_vitals',
    name: '护住要害',
    basePower: 2,
    cost: 1,
    tags: ['protection'],
    rarity: 'career',
    description: '抵消 3 点生命伤害。',
    effects: [{ type: 'REDUCE_HP_LOSS', amount: 3 }],
    assetId: 'card_guard_vitals',
  },
  {
    id: 'forced_entry',
    name: '强行突入',
    basePower: 5,
    cost: 2,
    tags: ['combat', 'escape'],
    rarity: 'career',
    description: '成功率高，但成功或失败都污染 +1。',
    effects: [{ type: 'ON_ANY_DELTA', delta: { pollution: 1 } }],
    assetId: 'card_forced_entry',
  },
  {
    id: 'improvised_weapon',
    name: '临时武器',
    basePower: 3,
    cost: 1,
    tags: ['combat'],
    rarity: 'career',
    description: '稳定战斗卡。',
    assetId: 'card_improvised_weapon',
  },
  {
    id: 'first_aid_kit',
    name: '急救包',
    basePower: 4,
    cost: 2,
    tags: ['medical'],
    rarity: 'career',
    description: '成功时生命 +2。',
    effects: [{ type: 'ON_SUCCESS_DELTA', delta: { hp: 2 } }],
    assetId: 'card_first_aid_kit',
  },
  {
    id: 'sedative',
    name: '镇定剂',
    basePower: 3,
    cost: 1,
    tags: ['medical', 'protection'],
    rarity: 'career',
    description: '理智 +2，但下一节点少抽 1 张牌。',
    effects: [
      { type: 'ON_SUCCESS_DELTA', delta: { sanity: 2 } },
      { type: 'NEXT_HAND_PENALTY', amount: 1 },
    ],
    assetId: 'card_sedative',
  },
  {
    id: 'autopsy',
    name: '尸检',
    basePower: 4,
    cost: 2,
    tags: ['medical', 'insight'],
    rarity: 'career',
    description: '成功时获得隐藏线索标记。',
    effects: [{ type: 'SET_FLAG', flagKey: 'hidden_autopsy_clue', flagValue: true }],
    assetId: 'card_autopsy',
  },
  {
    id: 'hemostasis',
    name: '止血',
    basePower: 2,
    cost: 1,
    tags: ['medical', 'protection'],
    rarity: 'career',
    description: '抵消一次流血或伤害惩罚。',
    effects: [{ type: 'REDUCE_HP_LOSS', amount: 1 }],
    assetId: 'card_hemostasis',
  },
  {
    id: 'blood_mark',
    name: '血印',
    basePower: 5,
    cost: 2,
    tags: ['ritual'],
    rarity: 'career',
    description: '使用后污染 +1。',
    effects: [{ type: 'ON_ANY_DELTA', delta: { pollution: 1 } }],
    assetId: 'card_blood_mark',
  },
  {
    id: 'reverse_prayer',
    name: '逆祷',
    basePower: 3,
    cost: 2,
    tags: ['ritual', 'protection'],
    rarity: 'career',
    description: '失败改为险胜，但污染 +2。',
    effects: [
      { type: 'FAILURE_TO_MIXED' },
      { type: 'ON_ANY_DELTA', delta: { pollution: 2 } },
    ],
    assetId: 'card_reverse_prayer',
  },
  {
    id: 'sealing_talisman',
    name: '封门符',
    basePower: 4,
    cost: 2,
    tags: ['ritual', 'protection'],
    rarity: 'career',
    description: '取消一次追击类惩罚。',
    effects: [{ type: 'REDUCE_HP_LOSS', amount: 2 }],
    assetId: 'card_sealing_talisman',
  },
  {
    id: 'speak_with_shadow',
    name: '与影交谈',
    basePower: 4,
    cost: 1,
    tags: ['ritual', 'insight'],
    rarity: 'career',
    description: '成功时获得线索，理智 -2。',
    effects: [
      { type: 'SET_FLAG', flagKey: 'shadow_dialogue_clue', flagValue: true },
      { type: 'ON_SUCCESS_DELTA', delta: { sanity: -2 } },
    ],
    assetId: 'card_speak_with_shadow',
  },
];

export const cardsById = Object.fromEntries(midnightHospitalCards.map((card) => [card.id, card])) as Record<
  CardDefinition['id'],
  CardDefinition
>;
