import type { CareerDefinition } from '../../../engine/types';

export const midnightHospitalCareers: CareerDefinition[] = [
  {
    id: 'investigator',
    name: '调查员',
    difficulty: '新手推荐',
    maxHp: 9,
    maxSanity: 10,
    strengths: ['insight', 'social'],
    weaknesses: ['combat', 'ritual'],
    passive: '每局第一次洞察失败时，改为险胜。',
    assetId: 'career_investigator',
    startingDeck: [
      'scene_reconstruction',
      'scene_reconstruction',
      'medical_record_questioning',
      'logic_loop',
      'calm_observation',
      'quick_search',
      'quick_search',
      'brace_yourself',
      'improvised_tool',
      'pollution_noise',
    ],
  },
  {
    id: 'cleaner',
    name: '清道夫',
    difficulty: '普通',
    maxHp: 12,
    maxSanity: 7,
    strengths: ['combat', 'protection'],
    weaknesses: ['insight', 'social'],
    passive: '每局第一次生命降到 0 时，保留 1 点生命。',
    assetId: 'career_cleaner',
    startingDeck: [
      'door_breaker',
      'door_breaker',
      'guard_vitals',
      'forced_entry',
      'improvised_weapon',
      'improvised_weapon',
      'brace_yourself',
      'quick_search',
      'run_through',
      'pollution_noise',
    ],
  },
  {
    id: 'physician',
    name: '医师',
    difficulty: '新手推荐',
    maxHp: 10,
    maxSanity: 9,
    strengths: ['medical', 'insight'],
    weaknesses: ['combat', 'stealth'],
    passive: '每两个节点后恢复 1 点生命。',
    assetId: 'career_physician',
    startingDeck: [
      'first_aid_kit',
      'first_aid_kit',
      'sedative',
      'autopsy',
      'hemostasis',
      'medical_record_questioning',
      'calm_observation',
      'quick_search',
      'improvised_tool',
      'pollution_noise',
    ],
  },
  {
    id: 'ritualist',
    name: '祭仪师',
    difficulty: '熟练玩家',
    maxHp: 8,
    maxSanity: 8,
    strengths: ['ritual', 'insight'],
    weaknesses: ['medical', 'combat'],
    passive: '每个节点可以选择污染 +1，使本次判定 +2。',
    assetId: 'career_ritualist',
    startingDeck: [
      'blood_mark',
      'blood_mark',
      'reverse_prayer',
      'sealing_talisman',
      'speak_with_shadow',
      'calm_observation',
      'quick_search',
      'brace_yourself',
      'improvised_tool',
      'pollution_noise',
    ],
  },
];

export const careersById = Object.fromEntries(midnightHospitalCareers.map((career) => [career.id, career])) as Record<
  CareerDefinition['id'],
  CareerDefinition
>;
