import { DIFFICULTY_CONFIG } from '../../../config/difficulty';
import type { CheckOutcome, EventNode, Hotspot, StateDelta } from '../../../engine/types';

const fragmentOutcome = (
  critical: StateDelta,
  success: StateDelta,
  mixed: StateDelta,
  failure: StateDelta,
): Record<CheckOutcome, StateDelta> => ({
  CRITICAL_SUCCESS: critical,
  SUCCESS: success,
  MIXED: mixed,
  FAILURE: failure,
});

export const midnightHospitalEvents: EventNode[] = [
  {
    id: 'mh_node_01_registration_hall',
    title: '挂号大厅',
    order: 1,
    difficulty: DIFFICULTY_CONFIG.nodeDifficulties[0],
    imageAssetId: 'mh_scene_registration_hall',
    recommendedTags: ['insight', 'social'],
    storyText:
      '午夜的挂号大厅只亮着一排冷白色的灯。自助挂号机不断吐出空白号单，前台后方坐着一名低头写字的护士。她没有抬头，却准确叫出了你的编号：1073。',
    resultTextKeys: {
      CRITICAL_SUCCESS: 'registration_hall_critical',
      SUCCESS: 'registration_hall_success',
      MIXED: 'registration_hall_mixed',
      FAILURE: 'registration_hall_failure',
    },
    actions: [
      {
        id: 'check_machine_record',
        label: '查看挂号机上的最后一条记录',
        description: '从不断吐出的号单里寻找编号规律。',
        preferredTags: ['insight'],
        timeCostSeconds: 45,
        riskLevel: 'low',
        onOutcome: fragmentOutcome({ fragments: 1, sanity: 1 }, { fragments: 1 }, { fragments: 1, sanity: -1 }, { sanity: -1, addFlags: { threat: 1 } }),
      },
      {
        id: 'question_front_desk_nurse',
        label: '询问前台护士',
        description: '试着让护士说出 1073 编号的来源。',
        preferredTags: ['social', 'insight'],
        timeCostSeconds: 40,
        riskLevel: 'medium',
        onOutcome: fragmentOutcome({ fragments: 1, sanity: 1 }, { fragments: 1 }, { fragments: 1, sanity: -1 }, { sanity: -1, addFlags: { threat: 1 } }),
      },
      {
        id: 'cross_hall_directly',
        label: '直接穿过大厅',
        description: '避开前台，快速抵达深处通道。',
        preferredTags: ['escape', 'stealth'],
        modifier: -1,
        timeCostSeconds: 30,
        riskLevel: 'high',
        onOutcome: fragmentOutcome({ fragments: 1, sanity: 1 }, { fragments: 1 }, { fragments: 1, sanity: -1 }, { sanity: -1, addFlags: { threat: 1 } }),
      },
    ],
  },
  {
    id: 'mh_node_02_nurse_station',
    title: '护士站',
    order: 2,
    difficulty: DIFFICULTY_CONFIG.nodeDifficulties[1],
    imageAssetId: 'mh_scene_nurse_station',
    recommendedTags: ['insight', 'medical'],
    storyText:
      '护士站的红灯一闪一闪，值班日志摊在桌上，最后一页写满了同一个名字。药柜深处传来玻璃瓶轻撞的声音，像有人在黑暗里整理药品。',
    resultTextKeys: {
      CRITICAL_SUCCESS: 'nurse_station_critical',
      SUCCESS: 'nurse_station_success',
      MIXED: 'nurse_station_mixed',
      FAILURE: 'nurse_station_failure',
    },
    actions: [
      {
        id: 'inspect_medical_cabinet',
        label: '检查病历柜',
        description: '翻找被红灯照亮的病历抽屉。',
        preferredTags: ['insight', 'medical'],
        timeCostSeconds: 45,
        riskLevel: 'low',
        onOutcome: fragmentOutcome({ fragments: 1, addFlags: { preview_node_3_tags: true } }, { fragments: 1 }, { fragments: 1, pollution: 1 }, { hp: -2 }),
      },
      {
        id: 'search_shift_log',
        label: '搜索值班日志',
        description: '查看最后一页重复出现的名字。',
        preferredTags: ['insight'],
        timeCostSeconds: 40,
        riskLevel: 'medium',
        onOutcome: fragmentOutcome({ fragments: 1, addFlags: { preview_node_3_tags: true } }, { fragments: 1 }, { fragments: 1, pollution: 1 }, { hp: -2 }),
      },
      {
        id: 'steal_access_card',
        label: '偷走护士的门禁卡',
        description: '趁黑暗里的动静靠近前拿走门禁卡。',
        preferredTags: ['stealth'],
        timeCostSeconds: 30,
        riskLevel: 'high',
        onOutcome: fragmentOutcome({ fragments: 1, addFlags: { preview_node_3_tags: true } }, { fragments: 1 }, { fragments: 1, pollution: 1 }, { hp: -2 }),
      },
    ],
  },
  {
    id: 'mh_node_03_inpatient_corridor',
    title: '住院部走廊',
    order: 3,
    difficulty: DIFFICULTY_CONFIG.nodeDifficulties[2],
    imageAssetId: 'mh_scene_inpatient_corridor',
    recommendedTags: ['stealth', 'social', 'combat'],
    storyText:
      '住院部走廊被拉长得不正常。307 病房的门虚掩着，里面有人轻声咳嗽。走廊尽头，一个穿病号服的人背对着你站着，腕带上的编号和你完全一致。',
    resultTextKeys: {
      CRITICAL_SUCCESS: 'corridor_critical',
      SUCCESS: 'corridor_success',
      MIXED: 'corridor_mixed',
      FAILURE: 'corridor_failure',
    },
    actions: [
      {
        id: 'pretend_patient',
        label: '假装自己是病人',
        description: '压低呼吸，让腕带编号替你说话。',
        preferredTags: ['social', 'stealth'],
        timeCostSeconds: 45,
        riskLevel: 'medium',
        onOutcome: fragmentOutcome({ fragments: 1, hp: 1 }, { fragments: 1 }, { fragments: 1, hp: -1 }, { hp: -2, sanity: -1 }),
      },
      {
        id: 'hide_room_307',
        label: '躲进 307 病房',
        description: '利用半开的病房门避开走廊尽头的人。',
        preferredTags: ['stealth', 'insight'],
        timeCostSeconds: 40,
        riskLevel: 'low',
        onOutcome: fragmentOutcome({ fragments: 1, hp: 1 }, { fragments: 1 }, { fragments: 1, hp: -1 }, { hp: -2, sanity: -1 }),
      },
      {
        id: 'rush_corridor',
        label: '正面冲过走廊',
        description: '趁它还没转身前冲向下一扇门。',
        preferredTags: ['combat', 'escape'],
        timeCostSeconds: 30,
        riskLevel: 'high',
        onOutcome: fragmentOutcome({ fragments: 1, hp: 1 }, { fragments: 1 }, { fragments: 1, hp: -1 }, { hp: -2, sanity: -1 }),
      },
    ],
  },
  {
    id: 'mh_node_04_operating_room',
    title: '手术室',
    order: 4,
    difficulty: DIFFICULTY_CONFIG.nodeDifficulties[3],
    imageAssetId: 'mh_scene_operating_room',
    recommendedTags: ['medical', 'ritual', 'insight'],
    minigameId: 'operating_room_anomaly',
    storyText:
      '手术室里没有病人，只有一张被白布盖住的手术台。无影灯缓慢旋转，却没有在地面留下影子。墙上的钟倒着走，秒针每退一格，门外就多一声脚步。',
    resultTextKeys: {
      CRITICAL_SUCCESS: 'operating_room_critical',
      SUCCESS: 'operating_room_success',
      MIXED: 'operating_room_mixed',
      FAILURE: 'operating_room_failure',
    },
    actions: [
      {
        id: 'lift_white_sheet',
        label: '掀开白布',
        description: '确认手术台上被隐藏的东西。',
        preferredTags: ['medical', 'insight'],
        timeCostSeconds: 45,
        riskLevel: 'medium',
        onOutcome: fragmentOutcome({ fragments: 1, pollution: -1 }, { fragments: 1 }, { fragments: 1, sanity: -2 }, { pollution: 1, sanity: -2 }),
      },
      {
        id: 'inspect_surgery_record',
        label: '检查手术记录',
        description: '读取空白记录夹里的压痕和顺序。',
        preferredTags: ['insight'],
        timeCostSeconds: 50,
        riskLevel: 'low',
        onOutcome: fragmentOutcome({ fragments: 1, pollution: -1 }, { fragments: 1 }, { fragments: 1, sanity: -2 }, { pollution: 1, sanity: -2 }),
      },
      {
        id: 'draw_sealing_mark',
        label: '在门口画下封闭符号',
        description: '抢在门外脚步抵达前封住入口。',
        preferredTags: ['ritual', 'protection'],
        timeCostSeconds: 45,
        riskLevel: 'medium',
        onOutcome: fragmentOutcome({ fragments: 1, pollution: -1 }, { fragments: 1 }, { fragments: 1, sanity: -2 }, { pollution: 1, sanity: -2 }),
      },
      {
        id: 'open_director_hidden_door',
        label: '打开院长办公室的暗门',
        description: '沿墙缝里的冷风找到隐藏通路。',
        preferredTags: ['insight', 'ritual'],
        modifier: -1,
        timeCostSeconds: 35,
        riskLevel: 'high',
        isCatchUp: true,
        onOutcome: fragmentOutcome({ fragments: 2, sanity: -1 }, { fragments: 2, pollution: 1 }, { fragments: 1, pollution: 1 }, { pollution: 2, hp: -2 }),
      },
    ],
  },
  {
    id: 'mh_node_05_morgue',
    title: '停尸间',
    order: 5,
    difficulty: DIFFICULTY_CONFIG.nodeDifficulties[4],
    imageAssetId: 'mh_scene_morgue',
    recommendedTags: ['ritual', 'insight', 'combat'],
    storyText:
      '停尸间的冷柜全部开着，只有 017 号柜紧紧锁死。柜门内侧传来指甲敲击金属的声音，节奏和你胸口的心跳完全一致。',
    resultTextKeys: {
      CRITICAL_SUCCESS: 'morgue_critical',
      SUCCESS: 'morgue_success',
      MIXED: 'morgue_mixed',
      FAILURE: 'morgue_failure',
    },
    actions: [
      {
        id: 'open_cabinet_017',
        label: '打开 017 号冷柜',
        description: '从柜门缝里确认心跳节奏的来源。',
        preferredTags: ['insight', 'medical'],
        timeCostSeconds: 45,
        riskLevel: 'medium',
        onOutcome: fragmentOutcome({ fragments: 1, addFlags: { final_escape_bonus: 1 } }, { fragments: 1 }, { fragments: 1, pollution: 2 }, { pollution: 2, hp: -2 }),
      },
      {
        id: 'break_morgue_power',
        label: '破坏停尸间电闸',
        description: '让金属冷柜和红灯一起熄灭。',
        preferredTags: ['combat', 'escape'],
        timeCostSeconds: 30,
        riskLevel: 'high',
        onOutcome: fragmentOutcome({ fragments: 1, addFlags: { final_escape_bonus: 1 } }, { fragments: 1 }, { fragments: 1, pollution: 2 }, { pollution: 2, hp: -2 }),
      },
      {
        id: 'ask_the_body',
        label: '向尸体询问天台密码',
        description: '用它的敲击声换取最后一段编号。',
        preferredTags: ['ritual', 'insight'],
        timeCostSeconds: 40,
        riskLevel: 'high',
        onOutcome: fragmentOutcome({ fragments: 1, addFlags: { final_escape_bonus: 1 } }, { fragments: 1 }, { fragments: 1, pollution: 2 }, { pollution: 2, hp: -2 }),
      },
    ],
  },
  {
    id: 'mh_node_06_elevator_shaft',
    title: '电梯井',
    order: 6,
    difficulty: DIFFICULTY_CONFIG.nodeDifficulties[5],
    imageAssetId: 'mh_scene_elevator_shaft',
    recommendedTags: ['combat', 'stealth', 'medical', 'escape'],
    storyText:
      '电梯停在井道中间，门缝外是一片黑。钢缆上挂着一串湿漉漉的腕带，每一张都写着曾经进入这里的编号。最上方那张还很新，墨迹没有干。',
    resultTextKeys: {
      CRITICAL_SUCCESS: 'elevator_critical',
      SUCCESS: 'elevator_success',
      MIXED: 'elevator_mixed',
      FAILURE: 'elevator_failure',
    },
    actions: [
      {
        id: 'climb_maintenance_ladder',
        label: '沿检修梯爬上去',
        description: '避开电梯厢，沿井壁寻找天台出口。',
        preferredTags: ['escape', 'stealth'],
        timeCostSeconds: 45,
        riskLevel: 'medium',
        onOutcome: fragmentOutcome({ fragments: 1, hp: 1 }, { fragments: 1 }, { fragments: 1, hp: -2 }, { hp: -3, pollution: 1 }),
      },
      {
        id: 'start_backup_power',
        label: '启动备用电源',
        description: '读取检修箱状态，让电梯上行。',
        preferredTags: ['medical', 'insight'],
        timeCostSeconds: 50,
        riskLevel: 'low',
        onOutcome: fragmentOutcome({ fragments: 1, hp: 1 }, { fragments: 1 }, { fragments: 1, hp: -2 }, { hp: -3, pollution: 1 }),
      },
      {
        id: 'cut_pursuer_hand',
        label: '切断追击者伸来的手',
        description: '在门缝合拢前夺回上升空间。',
        preferredTags: ['combat'],
        timeCostSeconds: 30,
        riskLevel: 'high',
        onOutcome: fragmentOutcome({ fragments: 1, hp: 1 }, { fragments: 1 }, { fragments: 1, hp: -2 }, { hp: -3, pollution: 1 }),
      },
    ],
  },
];

export const midnightHospitalFinalNode: EventNode = {
  id: 'mh_final_rooftop_lift',
  title: '天台升降梯',
  order: 7,
  difficulty: DIFFICULTY_CONFIG.finalDifficulty,
  imageAssetId: 'mh_scene_rooftop_lift',
  recommendedTags: ['escape', 'insight', 'ritual', 'combat'],
  isFinal: true,
  storyText:
    '天台的风把病院里的冷白灯光全部吹散。旧升降梯停在边缘，红色门禁灯像一只不肯闭上的眼睛。院长的影子从楼梯间蔓延出来，等待你输入最后的编号。',
  resultTextKeys: {
    CRITICAL_SUCCESS: 'final_critical',
    SUCCESS: 'final_success',
    MIXED: 'final_mixed',
    FAILURE: 'final_failure',
  },
  actions: [
    {
      id: 'input_fragment_code',
      label: '输入门禁碎片中的编号',
      description: '把收集到的门禁碎片顺序拼合。',
      preferredTags: ['insight', 'escape'],
      timeCostSeconds: 20,
      riskLevel: 'low',
      onOutcome: fragmentOutcome({}, {}, { pollution: 1, addFlags: { pollution_aftereffect: true } }, {}),
    },
    {
      id: 'force_lift_gate',
      label: '强行撬开升降梯门',
      description: '趁门锁短暂松动时撞开升降梯。',
      preferredTags: ['combat', 'escape'],
      timeCostSeconds: 15,
      riskLevel: 'high',
      onOutcome: fragmentOutcome({}, {}, { pollution: 1, addFlags: { pollution_aftereffect: true } }, { hp: -2 }),
    },
    {
      id: 'suppress_shadow_with_pollution',
      label: '用污染压制院长的影子',
      description: '让体内污染先一步吞下追来的黑影。',
      preferredTags: ['ritual', 'escape'],
      timeCostSeconds: 20,
      riskLevel: 'high',
      onOutcome: fragmentOutcome({ pollution: 1 }, { pollution: 1 }, { pollution: 2, addFlags: { pollution_aftereffect: true } }, { pollution: 2 }),
    },
  ],
};

export const operatingRoomHotspots: Hotspot[] = [
  { id: 'shadowless_lamp', label: '没有影子的无影灯', x: 0.52, y: 0.18, radius: 0.08 },
  { id: 'double_wristbands', label: '两张腕带', x: 0.48, y: 0.58, radius: 0.06 },
  { id: 'reversed_clock', label: '倒走的钟', x: 0.78, y: 0.25, radius: 0.06 },
];

export const eventsById = Object.fromEntries([
  ...midnightHospitalEvents.map((node) => [node.id, node]),
  [midnightHospitalFinalNode.id, midnightHospitalFinalNode],
]) as Record<string, EventNode>;
